#!/usr/bin/env python3
"""Compile the PIOS capsvc admin-console program from PicoScript source into
raw 32-bit bytecode words, matching the format capsvc_pico_host.c's pv_vm_run
expects (identical convention to httpd.c's picoweb_default_program).

Run from C:\\source\\picoscript so `picoscript_lang` is importable, e.g.:
    python compile_admin_capsule.py
"""
import sys
sys.path.insert(0, ".")
from picoscript_lang import Compiler

PREFIX = '{"ok":true,"capsule":"picoscript","path":"'
SUFFIX = '"}\n'


def emit_string_literal(lines, s):
    for ch in s:
        lines.append("Math.Sub(R1, R1, R1);")
        lines.append(f"Math.Add(R1, R1, {ord(ch)});")
        lines.append("Io.WriteByte(R1);")


def build_source():
    lines = ["Context.GetPath(R0);", "Net.Status(200);"]
    emit_string_literal(lines, PREFIX)
    lines.append("Io.Write(R0);")   # dynamic: echo the real request path span
    emit_string_literal(lines, SUFFIX)
    lines.append("Flow.Return();")
    return "\n".join(lines) + "\n"


def main():
    src = build_source()
    words = Compiler().compile(src)
    print(f"/* Auto-generated by compile_admin_capsule.py from picoscript_lang.py. */")
    print(f"/* {len(words)} words, {len(words) * 4} bytes. */")
    print("static const u32 capsvc_admin_default_program[] = {")
    for i in range(0, len(words), 6):
        chunk = words[i:i + 6]
        print("    " + ", ".join(f"0x{w:08X}u" for w in chunk) + ",")
    print("};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
