#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_hooks_js.py -- emit vm/pico_hooks.js from picoscript_lang.py.

Keeps the browser/Node VM's host-hook table in lock-step with the Python source,
exactly like vm/pico_hooks.h does for the C VM.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from picoscript_lang import (
    HOST_HOOK_CODES, HOST_HOOK_BASE, EXT_HOST_HOOK_BASE, NET_STATUS_BASE, NET_HEADER_BASE,
    NET_BODY_MARKER, NET_CLOSE_MARKER, CONTENT_TYPES, NAMED_CONSTANTS, NAMED_CONSTANT_I18N,
)
from pico_module import hook_table_version, MODULE_MAGIC, MODULE_ABI_VERSION

_HTV = hook_table_version()   # FNV-1a/32 content hash, identical in pico_module.py + picovm.js

L = []
L.append("// AUTO-GENERATED from picoscript_lang.py -- do not edit by hand.")
L.append("(function (root) {")
L.append("  var H = {")
L.append("    HOST_HOOK_BASE: 0x%04X," % HOST_HOOK_BASE)
L.append("    EXT_HOST_HOOK_BASE: 0x%04X," % EXT_HOST_HOOK_BASE)
L.append("    NET_STATUS_BASE: 0x%04X," % NET_STATUS_BASE)
L.append("    NET_HEADER_BASE: 0x%04X," % NET_HEADER_BASE)
L.append("    NET_BODY_MARKER: 0x%04X," % NET_BODY_MARKER)
L.append("    NET_CLOSE_MARKER: 0x%04X," % NET_CLOSE_MARKER)
L.append("    CONTENT_TYPES: {")
for k, v in CONTENT_TYPES.items():
    L.append('      0x%04X: "%s",' % (v, k))
L.append("    },")
L.append("    CONSTANTS: " + json.dumps(dict(sorted(NAMED_CONSTANTS.items())), sort_keys=True) + ",")
L.append("    CONSTANT_I18N: " + json.dumps(NAMED_CONSTANT_I18N, sort_keys=True, ensure_ascii=False) + ",")
L.append("    BY_CODE: {")
for (ns, m), code in sorted(HOST_HOOK_CODES.items(), key=lambda kv: kv[1]):
    L.append('      0x%02X: "%s.%s",' % (code, ns, m))
L.append("    }")
L.append("  };")
L.append("  function _canonConstant(name) {")
L.append("    if (name == null) return null;")
L.append("    var key = String(name).trim().toUpperCase();")
L.append('    if (key.indexOf("METHOD_") === 0) return "HTTP_" + key;')
L.append('    if (key.indexOf("STATUS_") === 0) return "HTTP_" + key;')
L.append('    if (key.indexOf("HTTPMETHOD.") === 0) return "HTTP_METHOD_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("HTTPSTATUS.") === 0) return "HTTP_STATUS_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("DAY.") === 0) return "DAY_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("MONTH.") === 0) return "MONTH_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("TZ.") === 0) return "TZ_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("TIMEZONE.") === 0) return "TZ_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("DST.") === 0) return "DST_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("CURRENCY.") === 0) return "CURRENCY_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("CURRENCYMINOR.") === 0) return "CURRENCY_MINOR_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("COUNTRY.") === 0) return "COUNTRY_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("UOM.") === 0) return "UOM_" + key.split(".", 2)[1];')
L.append('    if (key.indexOf("COLOR.") === 0) return "COLOR_" + key.split(".", 2)[1];')
L.append("    return key;")
L.append("  }")
L.append("  function _titleConstant(key) {")
L.append("    return String(key).replace(/[._]/g, ' ').toLowerCase().replace(/\\b\\w/g, function (c) { return c.toUpperCase(); });")
L.append("  }")
L.append("  function _defaultEnMeta(canonical, value) {")
L.append('    if (canonical.indexOf("CURRENCY_MINOR_") === 0) {')
L.append('      var cmi = canonical.slice("CURRENCY_MINOR_".length);')
L.append("      return { label: cmi + ' minor units', description: 'Decimal places used by ' + cmi + ' currency amounts.' };")
L.append("    }")
L.append('    if (canonical.indexOf("CURRENCY_") === 0) {')
L.append('      var cur = canonical.slice("CURRENCY_".length);')
L.append("      return { label: cur + ' currency', description: 'ISO-4217 numeric currency code for ' + cur + '.' };")
L.append("    }")
L.append('    if (canonical.indexOf("COUNTRY_") === 0) {')
L.append('      var co = canonical.slice("COUNTRY_".length);')
L.append("      return { label: co + ' country', description: 'ISO-3166-1 numeric country code for ' + co + '.' };")
L.append("    }")
L.append("    return { label: _titleConstant(canonical), description: 'Named constant value ' + value + '.' };")
L.append("  }")
L.append("  function _normalizeMetaEntry(entry) {")
L.append("    if (entry && typeof entry === 'object') {")
L.append("      var out = {};")
L.append("      if (entry.label != null) out.label = String(entry.label);")
L.append("      if (entry.description != null) out.description = String(entry.description);")
L.append("      return out;")
L.append("    }")
L.append("    if (typeof entry === 'string') return { label: entry };")
L.append("    return {};")
L.append("  }")
L.append("  function _userLocaleEntries(userDict, localeKey) {")
L.append("    var out = {};")
L.append("    if (!userDict || typeof userDict !== 'object') return out;")
L.append("    Object.keys(userDict).forEach(function (k) {")
L.append("      var v = userDict[k];")
L.append("      if (typeof v === 'string') out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(v);")
L.append("      else if (v && typeof v === 'object' && (v.label != null || v.description != null)) out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(v);")
L.append("    });")
L.append("    var base = String(localeKey || 'en').split('-', 2)[0];")
L.append("    [String(localeKey || 'en'), base].forEach(function (lk) {")
L.append("      var scoped = userDict[lk];")
L.append("      if (!scoped || typeof scoped !== 'object') return;")
L.append("      Object.keys(scoped).forEach(function (k) {")
L.append("        out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(scoped[k]);")
L.append("      });")
L.append("    });")
L.append("    return out;")
L.append("  }")
L.append("  H.describeConstant = function (name, locale, userDictionary) {")
L.append("    if (name == null) return null;")
L.append("    var raw = String(name).trim().toUpperCase();")
L.append("    if (!Object.prototype.hasOwnProperty.call(H.CONSTANTS, raw)) return null;")
L.append("    var value = Number(H.CONSTANTS[raw]);")
L.append("    var canonical = _canonConstant(raw);")
L.append("    var localeKey = String(locale || 'en');")
L.append("    var localeBase = localeKey.split('-', 2)[0];")
L.append("    var meta = _defaultEnMeta(canonical, value);")
L.append("    var en = (H.CONSTANT_I18N && H.CONSTANT_I18N.en && H.CONSTANT_I18N.en[canonical]) || {};")
L.append("    var loc = (H.CONSTANT_I18N && (H.CONSTANT_I18N[localeKey] || H.CONSTANT_I18N[localeBase]) && (H.CONSTANT_I18N[localeKey] || H.CONSTANT_I18N[localeBase])[canonical]) || {};")
L.append("    Object.assign(meta, en, loc);")
L.append("    var userEntries = _userLocaleEntries(userDictionary, localeKey);")
L.append("    Object.assign(meta, userEntries[canonical] || {}, userEntries[raw] || {});")
L.append("    return {")
L.append("      name: canonical,")
L.append("      value: value,")
L.append("      label: meta.label || canonical,")
L.append("      description: meta.description || ('Named constant value ' + value + '.'),")
L.append("      locale: localeKey")
L.append("    };")
L.append("  };")
L.append("  H.toLocale = function (name, locale, userDictionary, includeDescription) {")
L.append("    var m = H.describeConstant(name, locale, userDictionary);")
L.append("    if (!m) return null;")
L.append("    if (includeDescription === false) return m.label + ' (' + m.value + ')';")
L.append("    return m.label + ' (' + m.value + '): ' + m.description;")
L.append("  };")
L.append('  if (typeof module !== "undefined" && module.exports) { module.exports = H; }')
L.append("  else { root.PV_HOOKS = H; }")
L.append("})(typeof globalThis !== \"undefined\" ? globalThis : this);")

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vm", "pico_hooks.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("wrote", path, "with", len(HOST_HOOK_CODES), "hook codes")

# Mirror the C header (flat #define list, sorted by code) from the same table.
H = []
H.append("/* AUTO-GENERATED from picoscript_lang.py -- do not edit by hand. */")
H.append("#ifndef PICO_HOOKS_H")
H.append("#define PICO_HOOKS_H")
H.append("")
H.append("#define PV_HOST_HOOK_BASE  0x%04X" % HOST_HOOK_BASE)
H.append("#define PV_EXT_HOST_HOOK_BASE 0x%04X" % EXT_HOST_HOOK_BASE)
H.append("#define PV_NET_STATUS_BASE 0x%04X" % NET_STATUS_BASE)
H.append("#define PV_NET_HEADER_BASE 0x%04X" % NET_HEADER_BASE)
H.append("#define PV_NET_BODY_MARKER 0x%04X" % NET_BODY_MARKER)
H.append("#define PV_NET_CLOSE_MARKER 0x%04X" % NET_CLOSE_MARKER)
H.append("")
H.append("/* Module container (INV-23): wire format shared with pico_module.py / picovm.js. */")
H.append("#define PV_MODULE_MAGIC 0x%08X" % (MODULE_MAGIC & 0xFFFFFFFF))
H.append("#define PV_MODULE_ABI_VERSION %d" % MODULE_ABI_VERSION)
H.append("#define PV_HOOK_TABLE_VERSION 0x%08X" % (_HTV & 0xFFFFFFFF))
H.append("")
for (ns, m), code in sorted(HOST_HOOK_CODES.items(), key=lambda kv: kv[1]):
    name = ("PV_HOOK_%s_%s" % (ns, m)).upper()
    H.append("#define %-41s0x%02X" % (name, code))
H.append("")
H.append("/* Highest defined host-hook code. The compiler never emits a code above")
H.append(" * this, so pv_default_host uses it to tell a defined-but-unbound host-")
H.append(" * fillable primitive (INV-18 default: 0 / NOT_FOUND, mirroring")
H.append(" * picoscript_vm.py / picovm.js) from a genuinely unknown hook id in")
H.append(" * malformed bytecode, which fails closed (PV_FAULT_BAD_HOOK). */")
H.append("#define PV_HOOK_CODE_MAX 0x%02X" % max(HOST_HOOK_CODES.values()))
H.append("")
H.append("#endif")
hpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vm", "pico_hooks.h")
with open(hpath, "w", encoding="utf-8") as f:
    f.write("\n".join(H) + "\n")
print("wrote", hpath, "with", len(HOST_HOOK_CODES), "hook codes")
