// AUTO-GENERATED from picoscript_lang.py -- do not edit by hand.
(function (root) {
  var H = {
    HOST_HOOK_BASE: 0x7000,
    EXT_HOST_HOOK_BASE: 0x6000,
    NET_STATUS_BASE: 0x8000,
    NET_HEADER_BASE: 0x9000,
    NET_BODY_MARKER: 0xB000,
    NET_CLOSE_MARKER: 0xC000,
    CONTENT_TYPES: {
      0xA000: "text/html",
      0xA001: "text/plain",
      0xA002: "application/json",
      0xA003: "text/css",
      0xA004: "text/javascript",
      0xA005: "image/png",
      0xA006: "image/jpeg",
      0xA007: "application/octet-stream",
    },
    CONSTANTS: {"BITS_PER_BYTE": 8, "BYTES_PER_KIB": 1024, "BYTES_PER_MIB": 1048576, "CM_PER_METER": 100, "COLOR.BLACK": 0, "COLOR.BLUE": 255, "COLOR.CYAN": 65535, "COLOR.GRAY": 8421504, "COLOR.GREEN": 65280, "COLOR.GREY": 8421504, "COLOR.MAGENTA": 16711935, "COLOR.ORANGE": 16753920, "COLOR.RED": 16711680, "COLOR.WHITE": 16777215, "COLOR.YELLOW": 16776960, "COLOR_BLACK": 0, "COLOR_BLUE": 255, "COLOR_CYAN": 65535, "COLOR_GRAY": 8421504, "COLOR_GREEN": 65280, "COLOR_GREY": 8421504, "COLOR_MAGENTA": 16711935, "COLOR_ORANGE": 16753920, "COLOR_RED": 16711680, "COLOR_WHITE": 16777215, "COLOR_YELLOW": 16776960, "COUNTRY.AE": 784, "COUNTRY.AU": 36, "COUNTRY.BR": 76, "COUNTRY.CA": 124, "COUNTRY.CH": 756, "COUNTRY.CN": 156, "COUNTRY.DE": 276, "COUNTRY.DK": 208, "COUNTRY.ES": 724, "COUNTRY.FI": 246, "COUNTRY.FR": 250, "COUNTRY.GB": 826, "COUNTRY.HK": 344, "COUNTRY.IE": 372, "COUNTRY.IN": 356, "COUNTRY.IT": 380, "COUNTRY.JP": 392, "COUNTRY.KR": 410, "COUNTRY.MX": 484, "COUNTRY.NL": 528, "COUNTRY.NO": 578, "COUNTRY.NZ": 554, "COUNTRY.PL": 616, "COUNTRY.PT": 620, "COUNTRY.SE": 752, "COUNTRY.SG": 702, "COUNTRY.US": 840, "COUNTRY.ZA": 710, "COUNTRY_AE": 784, "COUNTRY_AU": 36, "COUNTRY_BR": 76, "COUNTRY_CA": 124, "COUNTRY_CH": 756, "COUNTRY_CN": 156, "COUNTRY_DE": 276, "COUNTRY_DK": 208, "COUNTRY_ES": 724, "COUNTRY_FI": 246, "COUNTRY_FR": 250, "COUNTRY_GB": 826, "COUNTRY_HK": 344, "COUNTRY_IE": 372, "COUNTRY_IN": 356, "COUNTRY_IT": 380, "COUNTRY_JP": 392, "COUNTRY_KR": 410, "COUNTRY_MX": 484, "COUNTRY_NL": 528, "COUNTRY_NO": 578, "COUNTRY_NZ": 554, "COUNTRY_PL": 616, "COUNTRY_PT": 620, "COUNTRY_SE": 752, "COUNTRY_SG": 702, "COUNTRY_US": 840, "COUNTRY_ZA": 710, "CURRENCY.AED": 784, "CURRENCY.AUD": 36, "CURRENCY.BRL": 986, "CURRENCY.CAD": 124, "CURRENCY.CHF": 756, "CURRENCY.CNY": 156, "CURRENCY.EUR": 978, "CURRENCY.GBP": 826, "CURRENCY.HKD": 344, "CURRENCY.INR": 356, "CURRENCY.JPY": 392, "CURRENCY.KRW": 410, "CURRENCY.MXN": 484, "CURRENCY.NOK": 578, "CURRENCY.NZD": 554, "CURRENCY.SEK": 752, "CURRENCY.SGD": 702, "CURRENCY.USD": 840, "CURRENCY.ZAR": 710, "CURRENCYMINOR.AED": 2, "CURRENCYMINOR.AUD": 2, "CURRENCYMINOR.BRL": 2, "CURRENCYMINOR.CAD": 2, "CURRENCYMINOR.CHF": 2, "CURRENCYMINOR.CNY": 2, "CURRENCYMINOR.EUR": 2, "CURRENCYMINOR.GBP": 2, "CURRENCYMINOR.HKD": 2, "CURRENCYMINOR.INR": 2, "CURRENCYMINOR.JPY": 0, "CURRENCYMINOR.KRW": 0, "CURRENCYMINOR.MXN": 2, "CURRENCYMINOR.NOK": 2, "CURRENCYMINOR.NZD": 2, "CURRENCYMINOR.SEK": 2, "CURRENCYMINOR.SGD": 2, "CURRENCYMINOR.USD": 2, "CURRENCYMINOR.ZAR": 2, "CURRENCY_AED": 784, "CURRENCY_AUD": 36, "CURRENCY_BRL": 986, "CURRENCY_CAD": 124, "CURRENCY_CHF": 756, "CURRENCY_CNY": 156, "CURRENCY_EUR": 978, "CURRENCY_GBP": 826, "CURRENCY_HKD": 344, "CURRENCY_INR": 356, "CURRENCY_JPY": 392, "CURRENCY_KRW": 410, "CURRENCY_MINOR_AED": 2, "CURRENCY_MINOR_AUD": 2, "CURRENCY_MINOR_BRL": 2, "CURRENCY_MINOR_CAD": 2, "CURRENCY_MINOR_CHF": 2, "CURRENCY_MINOR_CNY": 2, "CURRENCY_MINOR_EUR": 2, "CURRENCY_MINOR_GBP": 2, "CURRENCY_MINOR_HKD": 2, "CURRENCY_MINOR_INR": 2, "CURRENCY_MINOR_JPY": 0, "CURRENCY_MINOR_KRW": 0, "CURRENCY_MINOR_MXN": 2, "CURRENCY_MINOR_NOK": 2, "CURRENCY_MINOR_NZD": 2, "CURRENCY_MINOR_SEK": 2, "CURRENCY_MINOR_SGD": 2, "CURRENCY_MINOR_USD": 2, "CURRENCY_MINOR_ZAR": 2, "CURRENCY_MXN": 484, "CURRENCY_NOK": 578, "CURRENCY_NZD": 554, "CURRENCY_SEK": 752, "CURRENCY_SGD": 702, "CURRENCY_USD": 840, "CURRENCY_ZAR": 710, "DAY.FRIDAY": 5, "DAY.MONDAY": 1, "DAY.SATURDAY": 6, "DAY.SUNDAY": 7, "DAY.THURSDAY": 4, "DAY.TUESDAY": 2, "DAY.WEDNESDAY": 3, "DAYS_PER_WEEK": 7, "DAY_FRIDAY": 5, "DAY_MONDAY": 1, "DAY_SATURDAY": 6, "DAY_SUNDAY": 7, "DAY_THURSDAY": 4, "DAY_TUESDAY": 2, "DAY_WEDNESDAY": 3, "DEG_PER_RAD_Q16": 3754936, "DST.ACTIVE": 2, "DST.NONE": 0, "DST.OBSERVED": 1, "DST_ACTIVE": 2, "DST_NONE": 0, "DST_OBSERVED": 1, "GRAMS_PER_KILOGRAM": 1000, "HOURS_PER_DAY": 24, "HTTPMETHOD.CONNECT": 8, "HTTPMETHOD.DELETE": 4, "HTTPMETHOD.GET": 1, "HTTPMETHOD.HEAD": 5, "HTTPMETHOD.OPTIONS": 7, "HTTPMETHOD.PATCH": 6, "HTTPMETHOD.POST": 2, "HTTPMETHOD.PUT": 3, "HTTPMETHOD.TRACE": 9, "HTTPSTATUS.ACCEPTED": 202, "HTTPSTATUS.BAD_GATEWAY": 502, "HTTPSTATUS.BAD_REQUEST": 400, "HTTPSTATUS.CONFLICT": 409, "HTTPSTATUS.CREATED": 201, "HTTPSTATUS.FORBIDDEN": 403, "HTTPSTATUS.INTERNAL_SERVER_ERROR": 500, "HTTPSTATUS.NOT_FOUND": 404, "HTTPSTATUS.NOT_IMPLEMENTED": 501, "HTTPSTATUS.NO_CONTENT": 204, "HTTPSTATUS.OK": 200, "HTTPSTATUS.SERVICE_UNAVAILABLE": 503, "HTTPSTATUS.TOO_MANY_REQUESTS": 429, "HTTPSTATUS.UNAUTHORIZED": 401, "HTTPSTATUS.UNPROCESSABLE_ENTITY": 422, "HTTP_METHOD_CONNECT": 8, "HTTP_METHOD_DELETE": 4, "HTTP_METHOD_GET": 1, "HTTP_METHOD_HEAD": 5, "HTTP_METHOD_OPTIONS": 7, "HTTP_METHOD_PATCH": 6, "HTTP_METHOD_POST": 2, "HTTP_METHOD_PUT": 3, "HTTP_METHOD_TRACE": 9, "HTTP_STATUS_ACCEPTED": 202, "HTTP_STATUS_BAD_GATEWAY": 502, "HTTP_STATUS_BAD_REQUEST": 400, "HTTP_STATUS_CONFLICT": 409, "HTTP_STATUS_CREATED": 201, "HTTP_STATUS_FORBIDDEN": 403, "HTTP_STATUS_INTERNAL_SERVER_ERROR": 500, "HTTP_STATUS_NOT_FOUND": 404, "HTTP_STATUS_NOT_IMPLEMENTED": 501, "HTTP_STATUS_NO_CONTENT": 204, "HTTP_STATUS_OK": 200, "HTTP_STATUS_SERVICE_UNAVAILABLE": 503, "HTTP_STATUS_TOO_MANY_REQUESTS": 429, "HTTP_STATUS_UNAUTHORIZED": 401, "HTTP_STATUS_UNPROCESSABLE_ENTITY": 422, "INT16_MAX": 32767, "INT16_MIN": -32768, "INT24_MAX": 8388607, "INT24_MIN": -8388608, "INT32_MAX": 2147483647, "INT32_MIN": -2147483648, "INT8_MAX": 127, "INT8_MIN": -128, "MASK16": 65535, "MASK24": 16777215, "MASK32": 4294967295, "MASK8": 255, "METHOD_CONNECT": 8, "METHOD_DELETE": 4, "METHOD_GET": 1, "METHOD_HEAD": 5, "METHOD_OPTIONS": 7, "METHOD_PATCH": 6, "METHOD_POST": 2, "METHOD_PUT": 3, "METHOD_TRACE": 9, "MINUTES_PER_HOUR": 60, "MM_PER_METER": 1000, "MONTH.APRIL": 4, "MONTH.AUGUST": 8, "MONTH.DECEMBER": 12, "MONTH.FEBRUARY": 2, "MONTH.JANUARY": 1, "MONTH.JULY": 7, "MONTH.JUNE": 6, "MONTH.MARCH": 3, "MONTH.MAY": 5, "MONTH.NOVEMBER": 11, "MONTH.OCTOBER": 10, "MONTH.SEPTEMBER": 9, "MONTH_APRIL": 4, "MONTH_AUGUST": 8, "MONTH_DECEMBER": 12, "MONTH_FEBRUARY": 2, "MONTH_JANUARY": 1, "MONTH_JULY": 7, "MONTH_JUNE": 6, "MONTH_MARCH": 3, "MONTH_MAY": 5, "MONTH_NOVEMBER": 11, "MONTH_OCTOBER": 10, "MONTH_SEPTEMBER": 9, "MS_PER_SECOND": 1000, "PI_Q16": 205887, "RAD_PER_DEG_Q16": 1144, "SECONDS_PER_MINUTE": 60, "SIGN16": 32768, "SIGN24": 8388608, "SIGN32": 2147483648, "SIGN8": 128, "STATUS_ACCEPTED": 202, "STATUS_BAD_GATEWAY": 502, "STATUS_BAD_REQUEST": 400, "STATUS_CONFLICT": 409, "STATUS_CREATED": 201, "STATUS_FORBIDDEN": 403, "STATUS_INTERNAL_SERVER_ERROR": 500, "STATUS_NOT_FOUND": 404, "STATUS_NOT_IMPLEMENTED": 501, "STATUS_NO_CONTENT": 204, "STATUS_OK": 200, "STATUS_SERVICE_UNAVAILABLE": 503, "STATUS_TOO_MANY_REQUESTS": 429, "STATUS_UNAUTHORIZED": 401, "STATUS_UNPROCESSABLE_ENTITY": 422, "TIMEZONE.AMERICA_CHICAGO": 4, "TIMEZONE.AMERICA_DENVER": 5, "TIMEZONE.AMERICA_LOS_ANGELES": 6, "TIMEZONE.AMERICA_NEW_YORK": 3, "TIMEZONE.ASIA_DUBAI": 11, "TIMEZONE.ASIA_HONG_KONG": 9, "TIMEZONE.ASIA_SINGAPORE": 8, "TIMEZONE.ASIA_TOKYO": 7, "TIMEZONE.AUSTRALIA_SYDNEY": 10, "TIMEZONE.EUROPE_LONDON": 1, "TIMEZONE.EUROPE_PARIS": 2, "TIMEZONE.UTC": 0, "TZ.AMERICA_CHICAGO": 4, "TZ.AMERICA_DENVER": 5, "TZ.AMERICA_LOS_ANGELES": 6, "TZ.AMERICA_NEW_YORK": 3, "TZ.ASIA_DUBAI": 11, "TZ.ASIA_HONG_KONG": 9, "TZ.ASIA_SINGAPORE": 8, "TZ.ASIA_TOKYO": 7, "TZ.AUSTRALIA_SYDNEY": 10, "TZ.EUROPE_LONDON": 1, "TZ.EUROPE_PARIS": 2, "TZ.UTC": 0, "TZ_AMERICA_CHICAGO": 4, "TZ_AMERICA_DENVER": 5, "TZ_AMERICA_LOS_ANGELES": 6, "TZ_AMERICA_NEW_YORK": 3, "TZ_ASIA_DUBAI": 11, "TZ_ASIA_HONG_KONG": 9, "TZ_ASIA_SINGAPORE": 8, "TZ_ASIA_TOKYO": 7, "TZ_AUSTRALIA_SYDNEY": 10, "TZ_EUROPE_LONDON": 1, "TZ_EUROPE_PARIS": 2, "TZ_UTC": 0, "UINT16_MAX": 65535, "UINT24_MAX": 16777215, "UINT32_MAX": 4294967295, "UINT8_MAX": 255, "UOM.AMPERE": 4, "UOM.CANDELA": 7, "UOM.CELSIUS": 102, "UOM.GRAM": 101, "UOM.KELVIN": 5, "UOM.KILOGRAM": 2, "UOM.LITER": 100, "UOM.METER": 1, "UOM.MOLE": 6, "UOM.SECOND": 3, "UOM_AMPERE": 4, "UOM_CANDELA": 7, "UOM_CELSIUS": 102, "UOM_GRAM": 101, "UOM_KELVIN": 5, "UOM_KILOGRAM": 2, "UOM_LITER": 100, "UOM_METER": 1, "UOM_MOLE": 6, "UOM_SECOND": 3},
    CONSTANT_I18N: {"en": {"BITS_PER_BYTE": {"description": "Number of bits in one byte (8).", "label": "Bits per byte"}, "BYTES_PER_KIB": {"description": "Binary-size conversion constant (1024).", "label": "bytes per KiB"}, "BYTES_PER_MIB": {"description": "Binary-size conversion constant (1,048,576).", "label": "bytes per MiB"}, "CM_PER_METER": {"description": "Metric conversion constant (100).", "label": "centimetres per metre"}, "COLOR_BLACK": {"description": "24-bit RGB colour 0x000000.", "label": "Black"}, "COLOR_BLUE": {"description": "24-bit RGB colour 0x0000FF.", "label": "Blue"}, "COLOR_CYAN": {"description": "24-bit RGB colour 0x00FFFF.", "label": "Cyan"}, "COLOR_GRAY": {"description": "24-bit RGB colour 0x808080.", "label": "Gray"}, "COLOR_GREEN": {"description": "24-bit RGB colour 0x00FF00.", "label": "Green"}, "COLOR_MAGENTA": {"description": "24-bit RGB colour 0xFF00FF.", "label": "Magenta"}, "COLOR_ORANGE": {"description": "24-bit RGB colour 0xFFA500.", "label": "Orange"}, "COLOR_RED": {"description": "24-bit RGB colour 0xFF0000.", "label": "Red"}, "COLOR_WHITE": {"description": "24-bit RGB colour 0xFFFFFF.", "label": "White"}, "COLOR_YELLOW": {"description": "24-bit RGB colour 0xFFFF00.", "label": "Yellow"}, "COUNTRY_AE": {"description": "ISO-3166-1 numeric country code 784.", "label": "United Arab Emirates"}, "COUNTRY_AU": {"description": "ISO-3166-1 numeric country code 36.", "label": "Australia"}, "COUNTRY_BR": {"description": "ISO-3166-1 numeric country code 76.", "label": "Brazil"}, "COUNTRY_CA": {"description": "ISO-3166-1 numeric country code 124.", "label": "Canada"}, "COUNTRY_CH": {"description": "ISO-3166-1 numeric country code 756.", "label": "Switzerland"}, "COUNTRY_CN": {"description": "ISO-3166-1 numeric country code 156.", "label": "China"}, "COUNTRY_DE": {"description": "ISO-3166-1 numeric country code 276.", "label": "Germany"}, "COUNTRY_DK": {"description": "ISO-3166-1 numeric country code 208.", "label": "Denmark"}, "COUNTRY_ES": {"description": "ISO-3166-1 numeric country code 724.", "label": "Spain"}, "COUNTRY_FI": {"description": "ISO-3166-1 numeric country code 246.", "label": "Finland"}, "COUNTRY_FR": {"description": "ISO-3166-1 numeric country code 250.", "label": "France"}, "COUNTRY_GB": {"description": "ISO-3166-1 numeric country code 826.", "label": "United Kingdom"}, "COUNTRY_HK": {"description": "ISO-3166-1 numeric country code 344.", "label": "Hong Kong"}, "COUNTRY_IE": {"description": "ISO-3166-1 numeric country code 372.", "label": "Ireland"}, "COUNTRY_IN": {"description": "ISO-3166-1 numeric country code 356.", "label": "India"}, "COUNTRY_IT": {"description": "ISO-3166-1 numeric country code 380.", "label": "Italy"}, "COUNTRY_JP": {"description": "ISO-3166-1 numeric country code 392.", "label": "Japan"}, "COUNTRY_KR": {"description": "ISO-3166-1 numeric country code 410.", "label": "South Korea"}, "COUNTRY_MX": {"description": "ISO-3166-1 numeric country code 484.", "label": "Mexico"}, "COUNTRY_NL": {"description": "ISO-3166-1 numeric country code 528.", "label": "Netherlands"}, "COUNTRY_NO": {"description": "ISO-3166-1 numeric country code 578.", "label": "Norway"}, "COUNTRY_NZ": {"description": "ISO-3166-1 numeric country code 554.", "label": "New Zealand"}, "COUNTRY_PL": {"description": "ISO-3166-1 numeric country code 616.", "label": "Poland"}, "COUNTRY_PT": {"description": "ISO-3166-1 numeric country code 620.", "label": "Portugal"}, "COUNTRY_SE": {"description": "ISO-3166-1 numeric country code 752.", "label": "Sweden"}, "COUNTRY_SG": {"description": "ISO-3166-1 numeric country code 702.", "label": "Singapore"}, "COUNTRY_US": {"description": "ISO-3166-1 numeric country code 840.", "label": "United States"}, "COUNTRY_ZA": {"description": "ISO-3166-1 numeric country code 710.", "label": "South Africa"}, "CURRENCY_AED": {"description": "ISO-4217 numeric code 784.", "label": "UAE Dirham (AED)"}, "CURRENCY_AUD": {"description": "ISO-4217 numeric code 36.", "label": "Australian Dollar (AUD)"}, "CURRENCY_BRL": {"description": "ISO-4217 numeric code 986.", "label": "Brazilian Real (BRL)"}, "CURRENCY_CAD": {"description": "ISO-4217 numeric code 124.", "label": "Canadian Dollar (CAD)"}, "CURRENCY_CHF": {"description": "ISO-4217 numeric code 756.", "label": "Swiss Franc (CHF)"}, "CURRENCY_CNY": {"description": "ISO-4217 numeric code 156.", "label": "Chinese Yuan (CNY)"}, "CURRENCY_EUR": {"description": "ISO-4217 numeric code 978.", "label": "Euro (EUR)"}, "CURRENCY_GBP": {"description": "ISO-4217 numeric code 826.", "label": "Pound Sterling (GBP)"}, "CURRENCY_HKD": {"description": "ISO-4217 numeric code 344.", "label": "Hong Kong Dollar (HKD)"}, "CURRENCY_INR": {"description": "ISO-4217 numeric code 356.", "label": "Indian Rupee (INR)"}, "CURRENCY_JPY": {"description": "ISO-4217 numeric code 392.", "label": "Japanese Yen (JPY)"}, "CURRENCY_KRW": {"description": "ISO-4217 numeric code 410.", "label": "South Korean Won (KRW)"}, "CURRENCY_MXN": {"description": "ISO-4217 numeric code 484.", "label": "Mexican Peso (MXN)"}, "CURRENCY_NOK": {"description": "ISO-4217 numeric code 578.", "label": "Norwegian Krone (NOK)"}, "CURRENCY_NZD": {"description": "ISO-4217 numeric code 554.", "label": "New Zealand Dollar (NZD)"}, "CURRENCY_SEK": {"description": "ISO-4217 numeric code 752.", "label": "Swedish Krona (SEK)"}, "CURRENCY_SGD": {"description": "ISO-4217 numeric code 702.", "label": "Singapore Dollar (SGD)"}, "CURRENCY_USD": {"description": "ISO-4217 numeric code 840.", "label": "US Dollar (USD)"}, "CURRENCY_ZAR": {"description": "ISO-4217 numeric code 710.", "label": "South African Rand (ZAR)"}, "DAYS_PER_WEEK": {"description": "Unit conversion constant (7).", "label": "days per week"}, "DAY_FRIDAY": {"description": "ISO weekday index 5 (Friday).", "label": "Friday"}, "DAY_MONDAY": {"description": "ISO weekday index 1 (Monday).", "label": "Monday"}, "DAY_SATURDAY": {"description": "ISO weekday index 6 (Saturday).", "label": "Saturday"}, "DAY_SUNDAY": {"description": "ISO weekday index 7 (Sunday).", "label": "Sunday"}, "DAY_THURSDAY": {"description": "ISO weekday index 4 (Thursday).", "label": "Thursday"}, "DAY_TUESDAY": {"description": "ISO weekday index 2 (Tuesday).", "label": "Tuesday"}, "DAY_WEDNESDAY": {"description": "ISO weekday index 3 (Wednesday).", "label": "Wednesday"}, "DEG_PER_RAD_Q16": {"description": "Degrees-per-radian in Q16.16 format.", "label": "degrees per radian (Q16.16)"}, "DST_ACTIVE": {"description": "Current instant is inside the daylight saving period.", "label": "DST active now"}, "DST_NONE": {"description": "Zone does not observe daylight saving time.", "label": "No DST"}, "DST_OBSERVED": {"description": "Zone has daylight saving rules in its calendar.", "label": "DST observed"}, "GRAMS_PER_KILOGRAM": {"description": "Metric conversion constant (1000).", "label": "grams per kilogram"}, "HOURS_PER_DAY": {"description": "Unit conversion constant (24).", "label": "hours per day"}, "INT16_MAX": {"description": "Maximum signed 16-bit integer value.", "label": "i16 max"}, "INT16_MIN": {"description": "Minimum signed 16-bit integer value.", "label": "i16 min"}, "INT24_MAX": {"description": "Maximum signed 24-bit integer value.", "label": "i24 max"}, "INT24_MIN": {"description": "Minimum signed 24-bit integer value.", "label": "i24 min"}, "INT32_MAX": {"description": "Maximum signed 32-bit integer value.", "label": "i32 max"}, "INT32_MIN": {"description": "Minimum signed 32-bit integer value.", "label": "i32 min"}, "INT8_MAX": {"description": "Maximum signed 8-bit integer value.", "label": "i8 max"}, "INT8_MIN": {"description": "Minimum signed 8-bit integer value.", "label": "i8 min"}, "MASK16": {"description": "Bit mask for the low 16 bits (0xFFFF).", "label": "16-bit mask"}, "MASK24": {"description": "Bit mask for the low 24 bits (0xFFFFFF).", "label": "24-bit mask"}, "MASK32": {"description": "Bit mask for the low 32 bits (0xFFFFFFFF).", "label": "32-bit mask"}, "MASK8": {"description": "Bit mask for the low 8 bits (0xFF).", "label": "8-bit mask"}, "MINUTES_PER_HOUR": {"description": "Unit conversion constant (60).", "label": "minutes per hour"}, "MM_PER_METER": {"description": "Metric conversion constant (1000).", "label": "millimetres per metre"}, "MONTH_APRIL": {"description": "Month index 4 (April).", "label": "April"}, "MONTH_AUGUST": {"description": "Month index 8 (August).", "label": "August"}, "MONTH_DECEMBER": {"description": "Month index 12 (December).", "label": "December"}, "MONTH_FEBRUARY": {"description": "Month index 2 (February).", "label": "February"}, "MONTH_JANUARY": {"description": "Month index 1 (January).", "label": "January"}, "MONTH_JULY": {"description": "Month index 7 (July).", "label": "July"}, "MONTH_JUNE": {"description": "Month index 6 (June).", "label": "June"}, "MONTH_MARCH": {"description": "Month index 3 (March).", "label": "March"}, "MONTH_MAY": {"description": "Month index 5 (May).", "label": "May"}, "MONTH_NOVEMBER": {"description": "Month index 11 (November).", "label": "November"}, "MONTH_OCTOBER": {"description": "Month index 10 (October).", "label": "October"}, "MONTH_SEPTEMBER": {"description": "Month index 9 (September).", "label": "September"}, "MS_PER_SECOND": {"description": "Unit conversion constant (1000).", "label": "milliseconds per second"}, "PI_Q16": {"description": "Pi in fixed-point Q16.16 format.", "label": "pi (Q16.16)"}, "RAD_PER_DEG_Q16": {"description": "Radians-per-degree in Q16.16 format.", "label": "radians per degree (Q16.16)"}, "SECONDS_PER_MINUTE": {"description": "Unit conversion constant (60).", "label": "seconds per minute"}, "SIGN16": {"description": "Sign bit flag for signed 16-bit values (0x8000).", "label": "16-bit sign bit"}, "SIGN24": {"description": "Sign bit flag for signed 24-bit values (0x800000).", "label": "24-bit sign bit"}, "SIGN32": {"description": "Sign bit flag for signed 32-bit values (0x80000000).", "label": "32-bit sign bit"}, "SIGN8": {"description": "Sign bit flag for signed 8-bit values (0x80).", "label": "8-bit sign bit"}, "TZ_AMERICA_CHICAGO": {"description": "IANA zone America/Chicago (CST/CDT).", "label": "America/Chicago"}, "TZ_AMERICA_DENVER": {"description": "IANA zone America/Denver (MST/MDT).", "label": "America/Denver"}, "TZ_AMERICA_LOS_ANGELES": {"description": "IANA zone America/Los_Angeles (PST/PDT).", "label": "America/Los_Angeles"}, "TZ_AMERICA_NEW_YORK": {"description": "IANA zone America/New_York (EST/EDT).", "label": "America/New_York"}, "TZ_ASIA_DUBAI": {"description": "IANA zone Asia/Dubai (GST).", "label": "Asia/Dubai"}, "TZ_ASIA_HONG_KONG": {"description": "IANA zone Asia/Hong_Kong (HKT).", "label": "Asia/Hong_Kong"}, "TZ_ASIA_SINGAPORE": {"description": "IANA zone Asia/Singapore (SGT).", "label": "Asia/Singapore"}, "TZ_ASIA_TOKYO": {"description": "IANA zone Asia/Tokyo (JST).", "label": "Asia/Tokyo"}, "TZ_AUSTRALIA_SYDNEY": {"description": "IANA zone Australia/Sydney (AEST/AEDT).", "label": "Australia/Sydney"}, "TZ_EUROPE_LONDON": {"description": "IANA zone Europe/London (GMT/BST).", "label": "Europe/London"}, "TZ_EUROPE_PARIS": {"description": "IANA zone Europe/Paris (CET/CEST).", "label": "Europe/Paris"}, "TZ_UTC": {"description": "Coordinated Universal Time (no daylight saving transition).", "label": "UTC"}, "UINT16_MAX": {"description": "Maximum unsigned 16-bit integer value.", "label": "u16 max"}, "UINT24_MAX": {"description": "Maximum unsigned 24-bit integer value.", "label": "u24 max"}, "UINT32_MAX": {"description": "Maximum unsigned 32-bit integer value.", "label": "u32 max"}, "UINT8_MAX": {"description": "Maximum unsigned 8-bit integer value.", "label": "u8 max"}, "UOM_AMPERE": {"description": "SI base unit for electric current.", "label": "ampere (A)"}, "UOM_CANDELA": {"description": "SI base unit for luminous intensity.", "label": "candela (cd)"}, "UOM_CELSIUS": {"description": "Metric temperature scale in degrees Celsius.", "label": "degree Celsius (°C)"}, "UOM_GRAM": {"description": "Metric unit for mass (1/1000 kilogram).", "label": "gram (g)"}, "UOM_KELVIN": {"description": "SI base unit for temperature.", "label": "kelvin (K)"}, "UOM_KILOGRAM": {"description": "SI base unit for mass.", "label": "kilogram (kg)"}, "UOM_LITER": {"description": "Metric derived unit for volume.", "label": "liter (L)"}, "UOM_METER": {"description": "SI base unit for length.", "label": "meter (m)"}, "UOM_MOLE": {"description": "SI base unit for amount of substance.", "label": "mole (mol)"}, "UOM_SECOND": {"description": "SI base unit for time.", "label": "second (s)"}}},
    BY_CODE: {
      0x01: "Kernel.WaitIRQ",
      0x02: "Kernel.WaitSWIRQ",
      0x03: "Kernel.FireSWIRQ",
      0x04: "Kernel.ProfileStart",
      0x05: "Kernel.ProfileEnd",
      0x06: "Kernel.TracePoint",
      0x07: "Req.Seq",
      0x08: "Req.Principal",
      0x09: "Req.Method",
      0x0A: "Req.Path",
      0x0B: "Req.Header",
      0x0C: "Req.BodyMode",
      0x0D: "Req.BodyCount",
      0x0E: "Req.BodySpan",
      0x10: "Queue.Dequeue",
      0x11: "Queue.Enqueue",
      0x12: "Queue.Depth",
      0x13: "Queue.DequeueBatch",
      0x14: "Queue.EnqueueBatch",
      0x15: "Resp.Status",
      0x16: "Resp.Header",
      0x17: "Resp.Write",
      0x18: "Resp.Trailer",
      0x19: "Resp.Seal",
      0x1A: "Resp.End",
      0x1B: "Resp.Respond",
      0x1C: "Resp.Flush",
      0x1D: "Resp.Continue",
      0x1E: "Resp.EndStream",
      0x1F: "Resp.Upgrade",
      0x20: "Random.U32",
      0x21: "Utf8Writer.New",
      0x22: "Utf8Writer.Byte",
      0x23: "Utf8Writer.Int",
      0x24: "Utf8Writer.Span",
      0x25: "Utf8Writer.ToSpan",
      0x26: "Utf8Writer.Len",
      0x27: "Utf8Writer.Reset",
      0x28: "Utf8Reader.New",
      0x29: "Utf8Reader.Peek",
      0x2A: "Utf8Reader.Next",
      0x2B: "Utf8Reader.Int",
      0x2C: "Utf8Reader.SkipWs",
      0x2D: "Utf8Reader.Eof",
      0x2E: "Utf8Reader.Pos",
      0x2F: "Utf8Reader.Match",
      0x30: "Memory.ArenaInit",
      0x31: "Memory.ArenaAlloc",
      0x32: "Memory.ArenaReset",
      0x33: "Memory.ArenaStats",
      0x34: "Memory.Peek",
      0x35: "Memory.Poke",
      0x36: "Memory.Set",
      0x37: "Memory.Get",
      0x38: "Resp.Abort",
      0x39: "Resp.EarlyHints",
      0x3A: "Bits.And",
      0x3B: "Bits.Or",
      0x3C: "Bits.Xor",
      0x3D: "Bits.Shl",
      0x3E: "Bits.Shr",
      0x3F: "Bits.Sar",
      0x40: "Span.Make",
      0x41: "Span.Slice",
      0x42: "Span.Materialize",
      0x43: "Span.Len",
      0x44: "Span.Get",
      0x45: "Json.BeginObject",
      0x46: "Json.EndObject",
      0x47: "Json.BeginArray",
      0x48: "Json.EndArray",
      0x49: "Json.Key",
      0x4A: "Json.Str",
      0x4B: "Json.Int",
      0x4C: "Json.Bool",
      0x4D: "Json.Null",
      0x4E: "Json.Raw",
      0x4F: "Bits.Not",
      0x50: "Descriptor.Make",
      0x51: "Descriptor.SetFlags",
      0x52: "Descriptor.GetPtr",
      0x53: "Descriptor.GetLen",
      0x54: "Descriptor.GetFlags",
      0x55: "Descriptor.CopyBatch",
      0x56: "Dot8.Len",
      0x57: "Dot8.Of",
      0x58: "Lease.Acquire",
      0x59: "Lease.Release",
      0x5A: "Lease.Validate",
      0x5B: "Lease.CachedValidate",
      0x5C: "Lease.GetSpan",
      0x5D: "Lease.GetTypeHint",
      0x5E: "Status.Last",
      0x5F: "Memory.SetConst",
      0x60: "Storage.GetSchemaForPack",
      0x61: "Storage.SetSchemaForPack",
      0x62: "Storage.AddCard",
      0x63: "Storage.UpdateCard",
      0x64: "Storage.DeleteCard",
      0x65: "Storage.PatchCard",
      0x66: "Storage.ReadCard",
      0x67: "Storage.QueryCard",
      0x68: "Storage.UsePack",
      0x69: "Storage.EditCard",
      0x6A: "Storage.GetField",
      0x6B: "Storage.SetField",
      0x6C: "Storage.SetFieldStr",
      0x6D: "Storage.GetFieldStr",
      0x6E: "Storage.QueryResult",
      0x6F: "Storage.Ready",
      0x70: "Thread.YieldCounted",
      0x71: "Io.Write",
      0x72: "Io.WriteByte",
      0x73: "Xml.Open",
      0x74: "Xml.AttrName",
      0x75: "Xml.AttrValue",
      0x76: "Xml.OpenEnd",
      0x77: "Xml.Text",
      0x78: "Xml.Close",
      0x79: "Xml.Empty",
      0x7A: "Template.Compile",
      0x7B: "Template.Render",
      0x7C: "Arena.Mark",
      0x7D: "Arena.Rewind",
      0x7E: "Arena.Reset",
      0x80: "String.Concat",
      0x81: "String.Length",
      0x82: "String.Substring",
      0x83: "String.IndexOf",
      0x84: "String.Replace",
      0x85: "String.ToUpper",
      0x86: "String.ToLower",
      0x87: "String.Trim",
      0x88: "String.Split",
      0x89: "String.Join",
      0x8A: "String.StartsWith",
      0x8B: "String.EndsWith",
      0x8C: "String.SetReplace",
      0x8D: "String.Eq",
      0x90: "Number.Parse",
      0x91: "Number.ToString",
      0x92: "Number.ToHex",
      0x93: "Number.ToOctal",
      0x94: "Number.ToBinary",
      0x95: "Number.Abs",
      0x96: "Number.Floor",
      0x97: "Number.Ceiling",
      0x98: "Number.Round",
      0x99: "Number.Min",
      0x9A: "Number.Max",
      0xA0: "Maths.Sin",
      0xA1: "Maths.Cos",
      0xA2: "Maths.Tan",
      0xA3: "Maths.Sqrt",
      0xA4: "Maths.Power",
      0xA5: "Maths.Log",
      0xA6: "Maths.Log10",
      0xA7: "Maths.Exp",
      0xA8: "Maths.Random",
      0xA9: "Maths.RandomRange",
      0xAA: "Maths.Clamp",
      0xAB: "Maths.Lerp",
      0xB0: "DateTime.Now",
      0xB1: "DateTime.UtcNow",
      0xB2: "DateTime.Parse",
      0xB3: "DateTime.Format",
      0xB4: "DateTime.AddSeconds",
      0xB5: "DateTime.AddMinutes",
      0xB6: "DateTime.AddHours",
      0xB7: "DateTime.AddDays",
      0xB8: "DateTime.GetDayOfWeek",
      0xB9: "DateTime.GetDayOfYear",
      0xBA: "DateTime.UnixTimestamp",
      0xBB: "DateTime.DiffDays",
      0xBC: "DateTime.Year",
      0xBD: "DateTime.Month",
      0xBE: "DateTime.Day",
      0xC0: "Locale.GetCurrentLocale",
      0xC1: "Locale.SetLocale",
      0xC2: "Locale.FormatCurrency",
      0xC3: "Locale.FormatNumber",
      0xC4: "Locale.FormatDate",
      0xC5: "Locale.FormatTime",
      0xC6: "Locale.Translate",
      0xD0: "Environment.GetOsVersion",
      0xD1: "Environment.GetCpuCount",
      0xD2: "Environment.GetMemoryTotal",
      0xD3: "Environment.GetMemoryFree",
      0xD4: "Environment.GetHostname",
      0xD5: "Environment.GetTimeZone",
      0xD6: "Environment.GetProcessId",
      0xD7: "Environment.GetThreadId",
      0xD8: "Environment.GetElapsedTime",
      0xE0: "Context.GetVerb",
      0xE1: "Context.GetPath",
      0xE2: "Context.GetHost",
      0xE3: "Context.GetPort",
      0xE4: "Context.GetRemoteAddr",
      0xE5: "Context.GetUser",
      0xE6: "Context.GetPermissions",
      0xE7: "Context.GetHeaders",
      0xE8: "Context.GetQueryString",
      0xE9: "Context.GetBody",
      0xEA: "Context.SetScratchValue",
      0xEB: "Context.GetScratchValue",
      0xEC: "Context.GetRequestId",
      0xED: "Context.GetClientCert",
      0xEE: "Context.GetTraceId",
      0xF0: "Crypto.Sha256",
      0xF1: "Crypto.Sha512",
      0xF2: "Crypto.Blake2b",
      0xF3: "Crypto.Blake3",
      0xF4: "Crypto.HmacSha256",
      0xF5: "Crypto.HmacSha512",
      0xF6: "Crypto.Sign",
      0xF7: "Crypto.Verify",
      0xF8: "Crypto.Encrypt",
      0xF9: "Crypto.Decrypt",
      0xFA: "Crypto.GenerateKeyPair",
      0xFB: "Crypto.DeriveKey",
      0xFC: "Crypto.RandomBytes",
      0xFD: "Crypto.Md5",
      0xFE: "Crypto.Sha1",
      0x100: "Compress.BrotliCompress",
      0x101: "Compress.BrotliDecompress",
      0x102: "Compress.PicoCompress",
      0x103: "Compress.PicoDecompress",
      0x104: "Compress.GzipCompress",
      0x105: "Compress.GzipDecompress",
      0x106: "Compress.DeflateCompress",
      0x107: "Compress.DeflateDecompress",
      0x110: "X509.FetchCertificate",
      0x111: "X509.StoreCertificate",
      0x112: "X509.GenerateCSR",
      0x113: "X509.GenerateKeyPair",
      0x114: "X509.VerifyCertChain",
      0x115: "X509.GetCertInfo",
      0x116: "X509.IsCertValid",
      0x117: "X509.GetKeyHandle",
      0x120: "Auth.GetUserCredentials",
      0x121: "Auth.ValidateCredentials",
      0x122: "Auth.SwitchUserContext",
      0x123: "Auth.GetUserPermissions",
      0x124: "Auth.RequestToken",
      0x125: "Auth.GetToken",
      0x126: "Auth.ValidateToken",
      0x127: "Auth.SwitchTokenContext",
      0x128: "Auth.RefreshToken",
      0x129: "Auth.RevokeToken",
      0x130: "Http.ReadHeader",
      0x131: "Http.ReadBody",
      0x132: "Http.GenerateHeaders",
      0x133: "Http.GenerateResponse",
      0x134: "Http.ParseQuery",
      0x135: "Http.ParseForm",
      0x136: "Http.ParseJson",
      0x137: "Http.EncodeJson",
      0x138: "Http.Request",
      0x139: "Http.RespStatus",
      0x13A: "Http.RespHeaders",
      0x13B: "Http.RespBody",
      0x140: "Html.CreateNode",
      0x141: "Html.AddChildNode",
      0x142: "Html.RemoveChildNode",
      0x143: "Html.SetAttribute",
      0x144: "Html.GetAttribute",
      0x145: "Html.ParseTree",
      0x146: "Html.Encode",
      0x147: "Html.Decode",
      0x148: "Html.Serialize",
      0x149: "Html.QuerySelector",
      0x150: "Gpio.Count",
      0x151: "Gpio.SetDir",
      0x152: "Gpio.GetDir",
      0x153: "Gpio.SetPull",
      0x154: "Gpio.GetPull",
      0x155: "Gpio.Write",
      0x156: "Gpio.Read",
      0x160: "Pack.Use",
      0x161: "Card.Read",
      0x162: "Card.Write",
      0x163: "Card.Address",
      0x164: "Fifo.Open",
      0x165: "Fifo.Send",
      0x166: "Fifo.Recv",
      0x167: "Fifo.Poll",
      0x168: "Device.Open",
      0x169: "Device.Caps",
      0x16A: "Device.Close",
      0x16B: "Device.Status",
      0x170: "Stream.Open",
      0x171: "Stream.Next",
      0x172: "Stream.Span",
      0x173: "Stream.Submit",
      0x174: "Stream.Release",
      0x175: "Stream.Close",
      0x176: "Stream.SetSlice",
      0x177: "Stream.Slice",
      0x178: "Assert.Eq",
      0x179: "Assert.True",
      0x17A: "Assert.Count",
      0x17B: "Assert.Failed",
      0x17C: "Assert.Reset",
      0x180: "Event.Post",
      0x181: "Event.Next",
      0x182: "Event.Type",
      0x183: "Event.Target",
      0x184: "Event.Data",
      0x185: "Event.SetData",
      0x186: "Event.Count",
      0x188: "Ui.Window",
      0x189: "Ui.Panel",
      0x18A: "Ui.Label",
      0x18B: "Ui.Button",
      0x18C: "Ui.TextBox",
      0x18D: "Ui.Checkbox",
      0x18E: "Ui.Pos",
      0x18F: "Ui.Size",
      0x190: "Ui.SetText",
      0x191: "Ui.SetId",
      0x192: "Ui.SetValue",
      0x193: "Ui.Serialize",
      0x1A0: "Storage.SetSlice",
      0x1A1: "Storage.CardLen",
      0x1A2: "Storage.ReadSlice",
      0x1A3: "Storage.WriteSlice",
      0x1A4: "Storage.IsUserPack",
      0x1B0: "Req.SetSlice",
      0x1B1: "Req.BodySlice",
      0x1B2: "Req.BodyLen",
      0x1B3: "Event.SetSlice",
      0x1B4: "Event.DataSlice",
      0x1B5: "Event.DataLen",
      0x1B6: "Req.Param",
      0x1B7: "Req.ParamCount",
      0x1C0: "Query.BuildLookupFilter",
      0x1C1: "Query.BuildManyToManyMap",
      0x1D0: "Search.Clear",
      0x1D1: "Search.UpsertText",
      0x1D2: "Search.Delete",
      0x1D3: "Search.IndexPack",
      0x1D4: "Search.QueryText",
      0x1D5: "Search.SetVector",
      0x1D6: "Search.QueryHybrid",
      0x1D7: "Search.Result",
      0x1D8: "Search.Score",
      0x1D9: "Search.Plan",
      0x1DA: "Search.SetSemanticWeight",
      0x1DB: "Search.Configure",
      0x1DC: "Search.Compatible",
      0x1DD: "Search.Rebuild",
      0x1DE: "Search.SetFacet",
      0x1DF: "Search.SetNumber",
      0x1E0: "Tensor.SetShape",
      0x1E1: "Tensor.DotI8",
      0x1E2: "Tensor.MatVecI8",
      0x1E3: "Tensor.AddI32",
      0x1E4: "Tensor.MulI32",
      0x1E5: "Tensor.ScaleI32",
      0x1E6: "Tensor.ReluI32",
      0x1E7: "Tensor.RmsNormI32",
      0x1E8: "Tensor.RoPEI32",
      0x1E9: "Tensor.SoftmaxI32",
      0x1EA: "Tensor.ArgMaxI32",
      0x1EB: "Tensor.HasAccel",
      0x1F0: "BitLinear.SetShape",
      0x1F1: "BitLinear.MatVecTernary",
      0x1F2: "BitLinear.MatVecBitmap",
      0x1F3: "BitLinear.MatVecBase3",
      0x1F4: "BitLinear.HasFormat",
      0x200: "Search.ClearFields",
      0x201: "Search.Facets",
      0x202: "Search.FacetValue",
      0x203: "Search.FacetCount",
      0x204: "Search.Range",
      0x205: "Search.Save",
      0x206: "Search.Load",
      0x207: "Search.JournalUpsert",
      0x208: "Search.JournalDelete",
      0x209: "Search.JournalFacet",
      0x20A: "Search.JournalNumber",
      0x20B: "Search.JournalReplay",
      0x210: "Tokenizer.SetVocab",
      0x211: "Tokenizer.EncodeBytes",
      0x212: "Tokenizer.EncodeTrie",
      0x213: "Tokenizer.DecodeBytes",
      0x214: "Tokenizer.DecodeTrie",
      0x215: "Tokenizer.Count",
      0x216: "Tokenizer.Token",
      0x220: "Model.SetConfig",
      0x221: "Model.GetConfig",
      0x222: "Model.TensorView",
      0x223: "Model.TensorOffset",
      0x224: "Model.TensorRows",
      0x225: "Model.TensorCols",
      0x226: "Model.TensorFormat",
      0x227: "Model.ReadTensor",
      0x228: "Quant.AbsMax",
      0x229: "Quant.QuantI8",
      0x22A: "Quant.DequantI8",
      0x22B: "Quant.ApplyScale",
      0x22C: "Quant.GroupScale",
      0x230: "Kv.SetShape",
      0x231: "Kv.WriteK",
      0x232: "Kv.WriteV",
      0x233: "Kv.ReadK",
      0x234: "Kv.ReadV",
      0x235: "Kv.Len",
      0x236: "Kv.Clear",
      0x237: "Kv.SetHead",
      0x238: "Kv.WriteKH",
      0x239: "Kv.WriteVH",
      0x23A: "Kv.ReadKH",
      0x23B: "Kv.ReadVH",
      0x240: "Sampling.ArgMax",
      0x241: "Sampling.TopK",
      0x242: "Sampling.Temperature",
      0x243: "Sampling.ArgMaxRows",
      0x250: "Attention.SetShape",
      0x251: "Attention.Scores",
      0x252: "Attention.Mix",
      0x253: "Attention.Attend",
      0x260: "TextRender.Raw",
      0x261: "TextRender.Text",
      0x262: "TextRender.Open",
      0x263: "TextRender.Attr",
      0x264: "TextRender.OpenEnd",
      0x265: "TextRender.Close",
      0x266: "TextRender.Empty",
      0x267: "TextRender.Hole",
      0x268: "TextRender.Br",
      0x270: "Model.ReadTensorRow",
      0x271: "Model.SetBlock",
      0x272: "Model.ReadTensorBlock",
      0x273: "Model.MatVecI8Block",
      0x274: "BitLinear.MatVecTernaryBlock",
      0x275: "BitLinear.MatVecBitmapBlock",
      0x276: "BitLinear.MatVecBase3Block",
      0x280: "Process.Self",
      0x281: "Process.Parent",
      0x282: "Process.Spawn",
      0x283: "Process.Exit",
      0x284: "Process.Kill",
      0x285: "Process.Status",
      0x286: "Process.Wait",
      0x287: "Process.Args",
      0x288: "Env.Get",
      0x289: "Env.Set",
      0x28A: "Env.Count",
      0x28B: "Env.Key",
      0x290: "Timer.After",
      0x291: "Timer.Every",
      0x292: "Timer.Cancel",
      0x293: "Timer.Elapsed",
      0x294: "Scheduler.Tick",
      0x2A0: "Principal.Current",
      0x2A1: "Principal.HasRole",
      0x2A2: "Principal.Claims",
      0x2A3: "Capability.Has",
      0x2A4: "Capability.Request",
      0x2A5: "Capability.Drop",
      0x2A6: "Sandbox.Deny",
      0x2B0: "Error.SetHandler",
      0x2B1: "Error.HasHandler",
      0x2B2: "Error.Code",
      0x2B3: "Error.Detail",
      0x2B4: "Error.Resume",
      0x2B5: "Error.Clear",
      0x2B6: "Error.Raise",
      0x2B7: "Error.PopHandler",
      0x2C0: "Capsule.Call",
      0x2C1: "Capsule.Schedule",
      0x2C2: "Capsule.Jump",
      0x2C3: "Capsule.LoadModule",
      0x2C4: "Capsule.RunModule",
      0x2D0: "Base64.Encode",
      0x2D1: "Base64.Decode",
      0x2D2: "Base64.UrlDecode",
      0x2D3: "Base64.UrlEncode",
      0x2E0: "Net.Listen",
      0x2E1: "Net.Accept",
      0x2E2: "Net.Read",
      0x2E3: "Net.Write",
      0x2E4: "Net.Shutdown",
      0x2E5: "Net.PoolSize",
      0x2E6: "Net.Register",
      0x2F0: "Log.Write",
      0x2F1: "Log.Count",
      0x2F2: "Log.Level",
      0x2F3: "Log.Message",
      0x2F4: "Log.Clear",
      0x300: "Data.Lookup",
      0x301: "Data.FieldNum",
      0x302: "Data.FieldStr",
      0x310: "Encoding.AsciiEncode",
      0x311: "Encoding.AsciiDecode",
      0x312: "Encoding.Utf8Encode",
      0x313: "Encoding.Utf8Decode",
      0x314: "Encoding.Utf16LEEncode",
      0x315: "Encoding.Utf16LEDecode",
      0x316: "Encoding.Utf16BEEncode",
      0x317: "Encoding.Utf16BEDecode",
      0x318: "Encoding.Utf7Encode",
      0x319: "Encoding.Utf7Decode",
      0x31A: "Encoding.HexEncode",
      0x31B: "Encoding.HexDecode",
      0x320: "Map.New",
      0x321: "Map.Free",
      0x322: "Map.Clear",
      0x323: "Map.Count",
      0x324: "Map.Hash",
      0x325: "Map.PutII",
      0x326: "Map.GetII",
      0x327: "Map.HasI",
      0x328: "Map.DelI",
      0x329: "Map.PutIS",
      0x32A: "Map.GetIS",
      0x32B: "Map.PutNullI",
      0x32C: "Map.IsNullI",
      0x32D: "Map.PutSI",
      0x32E: "Map.GetSI",
      0x32F: "Map.HasS",
      0x330: "Map.DelS",
      0x331: "Map.PutSS",
      0x332: "Map.GetSS",
      0x333: "Map.PutNullS",
      0x334: "Map.IsNullS",
      0x335: "Map.KeyAt",
      0x336: "Map.KeySpanAt",
      0x337: "Map.ValAt",
      0x338: "Map.ValSpanAt",
      0x339: "Map.ValIsSpan",
      0x33A: "Map.Use",
      0x340: "Json.Parse",
      0x341: "Binary.ParseCard",
      0x342: "Binary.SerializeCard",
      0x343: "Binary.ParseEntity",
      0x344: "Binary.SerializeEntity",
      0x345: "Binary.SetKey",
      0x346: "Binary.Verify",
    }
  };
  function _canonConstant(name) {
    if (name == null) return null;
    var key = String(name).trim().toUpperCase();
    if (key.indexOf("METHOD_") === 0) return "HTTP_" + key;
    if (key.indexOf("STATUS_") === 0) return "HTTP_" + key;
    if (key.indexOf("HTTPMETHOD.") === 0) return "HTTP_METHOD_" + key.split(".", 2)[1];
    if (key.indexOf("HTTPSTATUS.") === 0) return "HTTP_STATUS_" + key.split(".", 2)[1];
    if (key.indexOf("DAY.") === 0) return "DAY_" + key.split(".", 2)[1];
    if (key.indexOf("MONTH.") === 0) return "MONTH_" + key.split(".", 2)[1];
    if (key.indexOf("TZ.") === 0) return "TZ_" + key.split(".", 2)[1];
    if (key.indexOf("TIMEZONE.") === 0) return "TZ_" + key.split(".", 2)[1];
    if (key.indexOf("DST.") === 0) return "DST_" + key.split(".", 2)[1];
    if (key.indexOf("CURRENCY.") === 0) return "CURRENCY_" + key.split(".", 2)[1];
    if (key.indexOf("CURRENCYMINOR.") === 0) return "CURRENCY_MINOR_" + key.split(".", 2)[1];
    if (key.indexOf("COUNTRY.") === 0) return "COUNTRY_" + key.split(".", 2)[1];
    if (key.indexOf("UOM.") === 0) return "UOM_" + key.split(".", 2)[1];
    if (key.indexOf("COLOR.") === 0) return "COLOR_" + key.split(".", 2)[1];
    return key;
  }
  function _titleConstant(key) {
    return String(key).replace(/[._]/g, ' ').toLowerCase().replace(/\b\w/g, function (c) { return c.toUpperCase(); });
  }
  function _defaultEnMeta(canonical, value) {
    if (canonical.indexOf("CURRENCY_MINOR_") === 0) {
      var cmi = canonical.slice("CURRENCY_MINOR_".length);
      return { label: cmi + ' minor units', description: 'Decimal places used by ' + cmi + ' currency amounts.' };
    }
    if (canonical.indexOf("CURRENCY_") === 0) {
      var cur = canonical.slice("CURRENCY_".length);
      return { label: cur + ' currency', description: 'ISO-4217 numeric currency code for ' + cur + '.' };
    }
    if (canonical.indexOf("COUNTRY_") === 0) {
      var co = canonical.slice("COUNTRY_".length);
      return { label: co + ' country', description: 'ISO-3166-1 numeric country code for ' + co + '.' };
    }
    return { label: _titleConstant(canonical), description: 'Named constant value ' + value + '.' };
  }
  function _normalizeMetaEntry(entry) {
    if (entry && typeof entry === 'object') {
      var out = {};
      if (entry.label != null) out.label = String(entry.label);
      if (entry.description != null) out.description = String(entry.description);
      return out;
    }
    if (typeof entry === 'string') return { label: entry };
    return {};
  }
  function _userLocaleEntries(userDict, localeKey) {
    var out = {};
    if (!userDict || typeof userDict !== 'object') return out;
    Object.keys(userDict).forEach(function (k) {
      var v = userDict[k];
      if (typeof v === 'string') out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(v);
      else if (v && typeof v === 'object' && (v.label != null || v.description != null)) out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(v);
    });
    var base = String(localeKey || 'en').split('-', 2)[0];
    [String(localeKey || 'en'), base].forEach(function (lk) {
      var scoped = userDict[lk];
      if (!scoped || typeof scoped !== 'object') return;
      Object.keys(scoped).forEach(function (k) {
        out[String(k).trim().toUpperCase()] = _normalizeMetaEntry(scoped[k]);
      });
    });
    return out;
  }
  H.describeConstant = function (name, locale, userDictionary) {
    if (name == null) return null;
    var raw = String(name).trim().toUpperCase();
    if (!Object.prototype.hasOwnProperty.call(H.CONSTANTS, raw)) return null;
    var value = Number(H.CONSTANTS[raw]);
    var canonical = _canonConstant(raw);
    var localeKey = String(locale || 'en');
    var localeBase = localeKey.split('-', 2)[0];
    var meta = _defaultEnMeta(canonical, value);
    var en = (H.CONSTANT_I18N && H.CONSTANT_I18N.en && H.CONSTANT_I18N.en[canonical]) || {};
    var loc = (H.CONSTANT_I18N && (H.CONSTANT_I18N[localeKey] || H.CONSTANT_I18N[localeBase]) && (H.CONSTANT_I18N[localeKey] || H.CONSTANT_I18N[localeBase])[canonical]) || {};
    Object.assign(meta, en, loc);
    var userEntries = _userLocaleEntries(userDictionary, localeKey);
    Object.assign(meta, userEntries[canonical] || {}, userEntries[raw] || {});
    return {
      name: canonical,
      value: value,
      label: meta.label || canonical,
      description: meta.description || ('Named constant value ' + value + '.'),
      locale: localeKey
    };
  };
  H.toLocale = function (name, locale, userDictionary, includeDescription) {
    var m = H.describeConstant(name, locale, userDictionary);
    if (!m) return null;
    if (includeDescription === false) return m.label + ' (' + m.value + ')';
    return m.label + ' (' + m.value + '): ' + m.description;
  };
  if (typeof module !== "undefined" && module.exports) { module.exports = H; }
  else { root.PV_HOOKS = H; }
})(typeof globalThis !== "undefined" ? globalThis : this);
