#!/usr/bin/env python3
"""Round-trip test for examples/selfhost_asm.pc."""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from picoscript_cfront import compile_c  # noqa: E402
from picoscript_il import lower_to_bytecode_safe  # noqa: E402
from picoscript_vm import PicoVM  # noqa: E402

INPUT_LEN_ADDR = 1000
INPUT_PTR = 1024


def _s32(v: int) -> int:
    v &= 0xFFFFFFFF
    return v - 0x100000000 if v & 0x80000000 else v


def _decode_print(vm: PicoVM) -> list[int]:
    return [_s32(int.from_bytes(chunk, "big")) for chunk in vm.output]


def _listing_from_words(words: list[int]) -> str:
    lines = []
    for word in words:
        lines.append(
            f"{(word >> 28) & 0xF} "
            f"{(word >> 24) & 0xF} "
            f"{(word >> 20) & 0xF} "
            f"{(word >> 16) & 0xF} "
            f"{word & 0xFFFF}"
        )
    return "\n".join(lines) + "\n"


def _seed_listing(vm: PicoVM, listing: str) -> None:
    data = listing.encode("ascii")
    assert len(data) < 65536 - INPUT_PTR
    vm.mem[INPUT_LEN_ADDR] = len(data) // 256
    vm.mem[INPUT_LEN_ADDR + 1] = len(data) % 256
    vm.mem[INPUT_PTR : INPUT_PTR + len(data)] = data


def test_selfhost_numeric_assembler_round_trips_native_bytecode() -> None:
    target_source = "int x = 40;\nint y = 2;\nprint(x * y);\n"
    native_words = lower_to_bytecode_safe(compile_c(target_source))
    listing = _listing_from_words(native_words)

    asm_source = open(os.path.join(ROOT, "examples", "selfhost_asm.pc"), encoding="utf-8").read()
    asm_words = lower_to_bytecode_safe(compile_c(asm_source))

    asm_vm = PicoVM()
    _seed_listing(asm_vm, listing)
    asm_vm.run(asm_words)

    emitted = b"".join(asm_vm.output)
    assert len(emitted) % 4 == 0
    generated_words = [
        int.from_bytes(emitted[i : i + 4], "big")
        for i in range(0, len(emitted), 4)
    ]

    assert generated_words == native_words

    generated_vm = PicoVM().run(generated_words)
    assert _decode_print(generated_vm) == [80]


if __name__ == "__main__":
    test_selfhost_numeric_assembler_round_trips_native_bytecode()
    print("PASS selfhost numeric assembler: generated bytecode matches native and prints 80")
