#!/usr/bin/env python3
"""Generate a deterministic PicoScript PicoWAL import/index program.

Parquet decoding remains a hosted build-time concern. The generated program
contains no Parquet dependency and writes documents/checkpoints exclusively
through the public pw_* PicoScript API.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import pyarrow.parquet as pq


def canonical(value):
    if isinstance(value, bytes):
        return {"$bytes": value.hex()}
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if isinstance(value, list):
        return [canonical(item) for item in value]
    if isinstance(value, dict):
        return {str(key): canonical(value[key]) for key in sorted(value)}
    return value


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=True)


def build_program(path: Path, pack: int, checkpoint_pack: int, start: int,
                  limit: int, text_column: str, field: int):
    parquet_hash = hashlib.sha256(path.read_bytes()).hexdigest()
    table = pq.read_table(path)
    stop = min(table.num_rows, start + limit)
    rows = []
    digest = hashlib.sha256()
    for record_id in range(start, stop):
        row = canonical(table.slice(record_id, 1).to_pylist()[0])
        encoded = json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        text = str(row.get(text_column, "")) if isinstance(row, dict) else ""
        digest.update(record_id.to_bytes(4, "little")); digest.update(encoded.encode("utf-8"))
        rows.append((record_id, encoded, text))
    manifest = {
        "format": "picowal-parquet-import-v1",
        "source_sha256": parquet_hash,
        "sequence_sha256": digest.hexdigest(),
        "start": start,
        "count": len(rows),
        "pack": pack,
        "text_column": text_column,
        "field": field,
    }
    lines = [
        "/* Generated by picowal_parquet_import.py; concatenate after picowal.pico. */",
        f"/* manifest {json.dumps(manifest, sort_keys=True)} */",
        "int pw_import_parquet_sample() {",
        "    int status = 0;",
    ]
    for record_id, encoded, text in rows:
        lines.append(f"    status = pw_put({pack}, {record_id}, {c_string(encoded)}, 0);")
        lines.append("    if (status != 0) { return status; }")
        lines.append(f"    pw_fulltext_upsert({pack}, {record_id}, {field}, {c_string(text)});")
    checkpoint = json.dumps(manifest, sort_keys=True, separators=(",", ":"))
    lines.append(f"    status = pw_put({checkpoint_pack}, 0, {c_string(checkpoint)}, 0);")
    lines.append("    if (status != 0) { return status; }")
    lines.append("    return pw_sync();")
    lines.append("}")
    return "\n".join(lines) + "\n", manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--pack", type=int, default=100)
    parser.add_argument("--checkpoint-pack", type=int, default=101)
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--limit", type=int, default=32)
    parser.add_argument("--text-column", default="text")
    parser.add_argument("--field", type=int, default=0)
    args = parser.parse_args()
    if args.start < 0 or args.limit < 0:
        parser.error("start and limit must be non-negative")
    program, manifest = build_program(args.input, args.pack, args.checkpoint_pack,
                                      args.start, args.limit, args.text_column, args.field)
    args.output.write_text(program, encoding="utf-8", newline="\n")
    print(json.dumps(manifest, sort_keys=True))


if __name__ == "__main__":
    main()
